# docker-compose -f docker-compose-dev.yml up
# How can one make a Docker Compose service build depend on another service?


version: "3.9"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # command: ["npm", "run", "docker:prisma-migrate"]
  jns-http-dev:
    build:
      network: host
      context: ./
      dockerfile: dockerfiles-dev/jns-http-dev.Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    depends_on:
      postgres_db:
        condition: service_healthy
  jns-ws-dev:
    build:
      network: host
      context: ./
      dockerfile: dockerfiles-dev/jns-ws-dev.Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    ports:
      - "3001:3001"
    depends_on:
      postgres_db:
        condition: service_healthy
  jns-web-dev:
    build:
      network: host
      context: ./
      dockerfile: dockerfiles-dev/jns-web-dev.Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    depends_on:
      postgres_db:
        condition: service_healthy
  prisma_migrate:
    build:
      network: host
      context: ./
      dockerfile: dockerfiles-dev/jns-http-dev.Dockerfile
    command: ["npx", "prisma", "docker:prisma-migrate"]
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres_db:5432/postgres
    depends_on:
      postgres_db:
        condition: service_healthy