name: Deploy to Staging
on:
  push:
    branches:
      - "main"

# added ""secrets wali thing 
# https://github.com/appleboy/ssh-action used to ssh into ec2.
jobs:
  redeploy_everything:
    name: Deploying Everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            cd BookMyShow-CI-CD
            git pull origin main
            pnpm install
            pnpm run build
            /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 delete http-server
            cd apps/http-server && /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 start apps/http-server --name http-server && cd ../..
            /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 delete ws-server
            cd apps/ws-server && /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 start apps/ws-server --name ws-server && cd ../..
            /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 delete web-server
            cd apps/web && /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 start apps/web --name web-server && cd ../../..
            /home/ubuntu/.nvm/versions/node/v20.20.0/bin/pm2 save


