name: Deploy to Staging
on:
  push:
    branches:
      - "main"

# added ""secrets wali thing 
# https://github.com/appleboy/ssh-action used to ssh into ec2.
jobs:
  redeploy_everything:
    name: Deploying Everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_IP }}
          username: ubuntu
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            cd BookMyShow-CI-CD
            git pull origin main
            pnpm install
            pnpm run build
            cd apps/http-server && pm2 restart http-server && cd ../..
            cd apps/ws-server && pm2 restart ws-server && cd ../..
            cd apps/web && pm2 restart web-server && cd ../..

